### ISSUE TITLE
Confusing representatives sections

### ISSUE THREAD

**Issue by sbidoul** [OCA-devel/repo-maintainer#23]
Currently a PSC definition looks like this:

```yaml
queue-maintainers:
  members:
    - guewen
    - lmignon
  name: Asynchronous job queue maintainers
  representatives:
    - simahawk
    - sbidoul
    - gurneyalex
queue-maintainers-psc-representative:
  members:
    - guewen
  name: Asynchronous job queue maintainers psc representative
  representatives: []
```

There seem to be some issues:

1/ `representatives` are declared as maintainers *of the team*. I think this is incorrect as the [team maintainer role](https://github.com/github/docs/blob/main/content/organizations/organizing-members-into-teams/assigning-the-team-maintainer-role-to-a-team-member.md) is meant to manage the team itself, and that job is now done by the repo-maintainer tool. This role does not give specific permissions on the repo.

2/ In the above example, it seams the `queue-maintainers-psc-representative` did not lead to the creation of a team in the repo? Should these teams have specific field to mention which repo role they should have?

Maybe I'm misunderstanding something, though.
